In [1]:
# Dependencies and Setup
import pandas as pd
import matplotlib.pyplot as plt
import json
import requests
import time
import seaborn as sns
from api_keys1 import API_KEY
from api_keys1 import gkey

In [ ]:
# import gmaps
# gmaps.configure(gkey)

In [2]:
#import sample csv
file="sample_df.csv"
pd.set_option('display.max_columns', None)
df = pd.read_csv(file, encoding='cp1252')
df.head()

,Unnamed: 0,acc_id,acc_date,acc_state,acc_city,fix_port,source,bus_type,industry_sector,device_category,device_type,tradename_or_generic,manufacturer,num_injured,age_youngest,gender,acc_desc,injury_desc,report,category,mechanical,op_error,employee,notes,year,Address
0,1986,918339,2006-06-12,CA,Chula Vista,F,California Division of Occupational Safety and...,Water park,water park,water slide,Family raft slide,family raft,WhiteWater West Industries Ltd.,1,12.0,F,Child got off raft and complained of back pain...,back pain,0,Body pain (normal motion),False,False,False,0,2006,"Chula Vista, CA"
1,5913,920274,2003-06-13,CA,Clovis,F,California Division of Occupational Safety and...,Water park,water park,water slide,Speed slide,speed slide,0,1,0.0,U,Unknown,Unknown,0,Unknown (not enough info),False,False,False,0,2003,"Clovis, CA"
2,345,916530,2007-09-08,TX,0,F,Texas Dept. of Insurance,Amusement park,amusement ride,coaster,Coaster - steel,steel sitdown coaster,Schwarzkopf Rides,1,14.0,M,Laceration,"At exit, guest was running and grabbed top of ...",0,Injured in queue or exit,False,False,False,0,2007,"0, TX"
3,7638,910279,2002-06-19,IL,0,P,Illinois Department of Labor,Carnival or rental,recreation,play equipment,Slide,dry slide,0,1,9.0,U,"Patron jumped onto ride and slid, which caused...",Possible injury to ankle,0,Impact: hit something in participatory attraction,False,False,False,0,2002,"0, IL"
4,5790,911785,2003-06-28,NC,Charlotte,U,North Carolina Dept. of Labor,Unknown,amusement ride,coaster,Coaster - unidentified,unidentified coaster,0,1,7.0,U,Child hit stomach on lap bar when ride jerked.,Stomach injury,0,Impact: hit something within ride vehicle,False,False,False,0,2003,"Charlotte, NC"

In [3]:
# Drop unneeded index column
df.drop("Unnamed: 0", axis=1, inplace=True) 
df.head()

,acc_id,acc_date,acc_state,acc_city,fix_port,source,bus_type,industry_sector,device_category,device_type,tradename_or_generic,manufacturer,num_injured,age_youngest,gender,acc_desc,injury_desc,report,category,mechanical,op_error,employee,notes,year,Address
0,918339,2006-06-12,CA,Chula Vista,F,California Division of Occupational Safety and...,Water park,water park,water slide,Family raft slide,family raft,WhiteWater West Industries Ltd.,1,12.0,F,Child got off raft and complained of back pain...,back pain,0,Body pain (normal motion),False,False,False,0,2006,"Chula Vista, CA"
1,920274,2003-06-13,CA,Clovis,F,California Division of Occupational Safety and...,Water park,water park,water slide,Speed slide,speed slide,0,1,0.0,U,Unknown,Unknown,0,Unknown (not enough info),False,False,False,0,2003,"Clovis, CA"
2,916530,2007-09-08,TX,0,F,Texas Dept. of Insurance,Amusement park,amusement ride,coaster,Coaster - steel,steel sitdown coaster,Schwarzkopf Rides,1,14.0,M,Laceration,"At exit, guest was running and grabbed top of ...",0,Injured in queue or exit,False,False,False,0,2007,"0, TX"
3,910279,2002-06-19,IL,0,P,Illinois Department of Labor,Carnival or rental,recreation,play equipment,Slide,dry slide,0,1,9.0,U,"Patron jumped onto ride and slid, which caused...",Possible injury to ankle,0,Impact: hit something in participatory attraction,False,False,False,0,2002,"0, IL"
4,911785,2003-06-28,NC,Charlotte,U,North Carolina Dept. of Labor,Unknown,amusement ride,coaster,Coaster - unidentified,unidentified coaster,0,1,7.0,U,Child hit stomach on lap bar when ride jerked.,Stomach injury,0,Impact: hit something within ride vehicle,False,False,False,0,2003,"Charlotte, NC"

In [4]:
#rename column
df.rename(columns = {'Address':'address'}, inplace = True)
df.head()

,acc_id,acc_date,acc_state,acc_city,fix_port,source,bus_type,industry_sector,device_category,device_type,tradename_or_generic,manufacturer,num_injured,age_youngest,gender,acc_desc,injury_desc,report,category,mechanical,op_error,employee,notes,year,address
0,918339,2006-06-12,CA,Chula Vista,F,California Division of Occupational Safety and...,Water park,water park,water slide,Family raft slide,family raft,WhiteWater West Industries Ltd.,1,12.0,F,Child got off raft and complained of back pain...,back pain,0,Body pain (normal motion),False,False,False,0,2006,"Chula Vista, CA"
1,920274,2003-06-13,CA,Clovis,F,California Division of Occupational Safety and...,Water park,water park,water slide,Speed slide,speed slide,0,1,0.0,U,Unknown,Unknown,0,Unknown (not enough info),False,False,False,0,2003,"Clovis, CA"
2,916530,2007-09-08,TX,0,F,Texas Dept. of Insurance,Amusement park,amusement ride,coaster,Coaster - steel,steel sitdown coaster,Schwarzkopf Rides,1,14.0,M,Laceration,"At exit, guest was running and grabbed top of ...",0,Injured in queue or exit,False,False,False,0,2007,"0, TX"
3,910279,2002-06-19,IL,0,P,Illinois Department of Labor,Carnival or rental,recreation,play equipment,Slide,dry slide,0,1,9.0,U,"Patron jumped onto ride and slid, which caused...",Possible injury to ankle,0,Impact: hit something in participatory attraction,False,False,False,0,2002,"0, IL"
4,911785,2003-06-28,NC,Charlotte,U,North Carolina Dept. of Labor,Unknown,amusement ride,coaster,Coaster - unidentified,unidentified coaster,0,1,7.0,U,Child hit stomach on lap bar when ride jerked.,Stomach injury,0,Impact: hit something within ride vehicle,False,False,False,0,2003,"Charlotte, NC"

In [5]:
#Change data types
df["acc_date"] = pd.to_datetime(df["acc_date"])
df["year"] = df["year"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   acc_id                1000 non-null   int64
 1   acc_date              1000 non-null   datetime64[ns]
 2   acc_state             1000 non-null   object
 3   acc_city              1000 non-null   object
 4   fix_port              1000 non-null   object
 5   source                1000 non-null   object
 6   bus_type              1000 non-null   object
 7   industry_sector       1000 non-null   object
 8   device_category       1000 non-null   object
 9   device_type           1000 non-null   object
 10  tradename_or_generic  1000 non-null   object
 11  manufacturer          1000 non-null   object
 12  num_injured           1000 non-null   int64
 13  age_youngest          1000 non-null   float64
 14  gender                1000 non-null   object
 15  acc_desc              1000 non-null   object
 16  injury_desc           1000 non-null   object
 17  report                1000 non-null   object
 18  category              1000 non-null   object
 19  mechanical            1000 non-null   bool
 20  op_error              1000 non-null   bool
 21  employee              1000 non-null   bool
 22  notes                 1000 non-null   object
 23  year                  1000 non-null   int64
 24  address               1000 non-null   object
dtypes: bool(3), datetime64[ns](1), float64(1), int64(3), object(17)
memory usage: 174.9+ KB

In [ ]:
# df["acc_city"] = df.acc_city.replace("None", "na")
# df

In [ ]:
address = df.address[0]
address

In [ ]:
#Get location data from opwnweathermap.org

url = f"http://api.openweathermap.org/geo/1.0/direct?q={address}&appid={API_KEY}"
response = requests.get(url)

data = response.json()

if (len(data) > 0):
    location = data[0]
    print(location)

In [ ]:
# #Loop to get location info for all addresses

# rows = []

# for address in df1.address:
#     print(address)
    
#     # create URL
#     url = f"http://api.openweathermap.org/geo/1.0/direct?q={address}&appid={API_KEY}"
#     response = requests.get(url)
    
#     # get data
#     data = response.json()

#     if (len(data) > 0):
#         location = data[0]
        
#         # parse data
#         lat = location["lat"]
#         lon = location["lon"]
#         city = location["name"]
#         state = location.get("state")
        
#         # make row
#         row = {"latitude": lat,
#               "longitude": lon,
#               "clean_city": city,
#               "clean_state": state}
        
#     else:
#         row = {"latitude": np.nan,
#               "longitude": np.nan,
#               "clean_city": None,
#               "clean_state": None}
    
#     rows.append(row)
#     time.sleep(1)

In [ ]:
# #Google map

# # get data
# data = df_win.loc[:, ["latitude", "longitude"]].dropna()

# # Create BASE, init the graph
# figure_layout = {
#     'width': '800px',
#     'height': '600px',
#     'border': '0px',
#     'padding': '1px',
#     'margin': '0 auto 0 auto'
# }
# fig = gmaps.figure(layout=figure_layout, map_type='HYBRID')

# # init the overlay layers
# heat = gmaps.heatmap_layer(data)
# fig.add_layer(heat)


# # show the plot
# fig

In [ ]:
# #BAR CHART HORIZONTAL 
# # step 1 - get the data
# states = df.clean_state.value_counts(ascending=True)

# x = states.index
# y = states.values

# # step 2 - make/init the plot
# fig = plt.figure(figsize=(10, 8))
# plt.barh(x, y, color="pink")

# # step 3 - customization
# plt.xlabel("# of Contestants per State", fontname = "Helvetica", fontsize=16)
# plt.ylabel("States", fontname = "Helvetica", fontsize=10)
# plt.title("Home States of Contestants", fontsize=24, fontweight="bold", fontname = "Helvetica")
# plt.xticks(fontsize=10, rotation=0)
# plt.yticks(fontsize=10)
# plt.grid(axis="x", alpha=0.25)

# # step 4 - show/save the plot
# plt.show()

In [ ]:
# #Bar chart 
# states = df.loc[df["Season Bin"] == "15-21"].clean_state.value_counts().head(5)
# x = states.index
# y = states.values

# # step 2 - make/init the plot
# fig = plt.figure(figsize=(10, 8))
# plt.bar(x, y,  color="pink")

# # step 3 - customization
# plt.ylabel("# of Contestants", fontname = "Helvetica", fontsize=16)
# plt.title("Seasons 15-21: Top 5 States Contestants Are From", fontsize=22, fontweight="bold", fontname = "Helvetica")
# plt.xticks(fontsize=14, rotation=0)

# plt.grid(axis="y", alpha=0.25)

# # step 4 - show/save the plot
# plt.show()

In [ ]:
df